In [6]:
import pandas as pd
import numpy as np
import scipy.sparse

In [7]:
arr = np.arange(10)

In [8]:
# arr.max()
np.max(arr)

np.int64(9)

## Space matrix
- sparce.csr_matrix(matrix or ndarray(2d))
- space_matrix.toarray() returns decompressed ndarray
- sparce.matrix.todense() return decompressed matrix

a = np.matrix(((10, 3, 0), (3,0,0), (0,0,0)))
print(a)
print(f"a.shape: {a.shape}")
print(f"count non-zeros: {np.count_nonzero(a)}")

In [15]:
compressedA = scipy.sparse.csr_matrix(a)
print(f"CompressedA: {compressedA}\ntype: {type(compressedA)}")

CompressedA: <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	10
  (0, 1)	3
  (1, 0)	3
type: <class 'scipy.sparse._csr.csr_matrix'>


In [16]:
recoveredA = compressedA.toarray()
print(f"recoveredA: {recoveredA}")
print(f"type: {type(recoveredA)}")

recoveredA: [[10  3  0]
 [ 3  0  0]
 [ 0  0  0]]
type: <class 'numpy.ndarray'>


In [17]:
recoveredA = compressedA.todense()
print(f"recoveredA: {recoveredA}\n type: {type(recoveredA)}")

recoveredA: [[10  3  0]
 [ 3  0  0]
 [ 0  0  0]]
 type: <class 'numpy.matrix'>


## Pandas 
### Series


In [37]:
labels = ['a','b','e']
print(f"lables: {lables}")

my_data = [10, 20, 30]
np.array(my_data)

d = dict(zip(lables,my_data))
print(f"d: {d}")

lables: ['a', 'b', 'e']
d: {'a': 10, 'b': 20, 'e': 30}


- Works with both list and dictionary

In [41]:
# df = pd.Series(data = my_data, index=labels)
s = pd.Series(my_data, labels)
s 
s

a    10
b    20
e    30
dtype: int64

In [45]:
df = pd.Series(d)
print(f"df: {df}")
type(df)

df: a    10
b    20
e    30
dtype: int64


pandas.core.series.Series

In [47]:
# You can also convert the functions into series
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [57]:
series1 = pd.Series([1,2,3,4],['a','b','c', 'c'])
series2 = pd.Series([1,2,3,4],['a','bb','c', 'c'])
series1

a    1
b    2
c    3
c    4
dtype: int64

In [58]:
print(series1 + series2)

a     2.0
b     NaN
bb    NaN
c     6.0
c     7.0
c     7.0
c     8.0
dtype: float64


## Data frame
- Df are more like excel, having rows and cols
- Where column is pandas series

In [65]:
df = pd.DataFrame(np.random.randn(5,4), ['A', 'B', 'C', 'D', 'E'], ['K', 'L', 'M', 'J'])
print(df)
type(df)

          K         L         M         J
A  0.999113  0.530056  0.002992  0.391065
B  0.603702 -1.681669  0.848197  0.296070
C -0.669739 -1.084484  0.320881  0.652806
D  1.654424 -0.080905  0.520208 -0.020171
E  0.280381  0.719766  0.681269  1.703602


pandas.core.frame.DataFrame

In [69]:
np.random.seed(10)
np.random.rand(5,4)

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [71]:
np.random.seed(10)
np.random.rand(5,4)

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [75]:
df['K'] = df['J'] + df['M']

In [76]:
df['K']

A    0.394058
B    1.144266
C    0.973687
D    0.500037
E    2.384871
Name: K, dtype: float64

In [77]:
df = df.drop('J', axis=1)
df

K         L         M
A  0.394058  0.530056  0.002992
B  1.144266 -1.681669  0.848197
C  0.973687 -1.084484  0.320881
D  0.500037 -0.080905  0.520208
E  2.384871  0.719766  0.681269

In [78]:
df.drop('E', axis=0)

K         L         M
A  0.394058  0.530056  0.002992
B  1.144266 -1.681669  0.848197
C  0.973687 -1.084484  0.320881
D  0.500037 -0.080905  0.520208

In [79]:
df

K         L         M
A  0.394058  0.530056  0.002992
B  1.144266 -1.681669  0.848197
C  0.973687 -1.084484  0.320881
D  0.500037 -0.080905  0.520208
E  2.384871  0.719766  0.681269

In [80]:
df.shape

(5, 3)

In [81]:
df.drop('K', axis=1, inplace=True)

In [82]:
df

L         M
A  0.530056  0.002992
B -1.681669  0.848197
C -1.084484  0.320881
D -0.080905  0.520208
E  0.719766  0.681269